version: '3.8'

services:
  nginx:
    container_name: "calc_test_nginx"
    build: ./docker_images/nginx
    volumes:
      - ./app:/var/www/html
    depends_on:
      - php

  php:
    container_name: "calc_test_php"
    build: ./docker_images/php
    volumes:
      - ./app:/var/www/html
